- name: Db Config
  hosts: localhost
  vars_files:
    - var_file.yml
  tasks:
    - name: Service Principal Login
      command: >
        az login --service-principal
        --username "{{ azconfig.client_id }}"
        --password "{{ azconfig.secret }}"
        --tenant "{{ azconfig.tenant_id }}"
    - name: Get Databases Full Info
      community.postgresql.postgresql_info:
        login_host: "{{ database_config.login_host }}"
        login_user: "{{ database_config.login_user }}"
        login_password: "{{ database_config.login_password }}"
        ssl_mode: "require"
        db: postgres
        filter: "databases"
      register: db_list_full_info
    - name: Get Databases Names and Filter defaults
      set_fact:
        db_names: "{{ db_list_full_info['databases'] | dict2items | map(attribute='key') | list | difference(['postgres', 'template1', 'azure_maintenance', 'azure_sys']) }}"
    - name: Print database names
      debug:
        var: db_names
    - name: Configure Databases
      ansible.builtin.include_tasks: database_config.yml
      loop: "{{ db_names }}"
    - name: Create Developer Role
      ansible.builtin.include_tasks: azure_ad_developer_config.yml
      loop: "{{ db_names }}"    
    - name: Create Aoplication User
      ansible.builtin.include_tasks: application_user_config.yml
      loop: "{{ db_names }}"
    - name: Logout from Azure
      command: >
        az logout