- name: Alter schema owner
  community.postgresql.postgresql_schema:
    login_host: "{{ common_config.login_host }}"
    login_user: "{{ common_config.login_user }}"
    login_password: "{{ common_config.login_password }}"
    db: "{{ item.db }}"
    name: public
    owner: "{{ common_config.owner }}"
- name: Revoke create on schema public
  community.postgresql.postgresql_privs:
    login_host: "{{ common_config.login_host }}"
    login_user: "{{ common_config.login_user }}"
    login_password: "{{ common_config.login_password }}"
    db: "{{ item.db }}"
    state: absent
    type: schema
    objs: public
    privs: create
    role: public
- name: Revoke all on database from public
  community.postgresql.postgresql_privs:
    login_host: "{{ common_config.login_host }}"
    login_user: "{{ common_config.login_user }}"
    login_password: "{{ common_config.login_password }}"
    db: "{{ item.db }}"
    state: absent
    type: database
    privs: all
    role: public
