- name: Db Config
  hosts: localhost
  vars_files:
    - var_file.yml
  tasks:
    - name: Print vars
      debug:
        var: common_config
    - name: Print database
      debug:
        var: database_names
    - name: Utility present
      ansible.builtin.package:
        name: python3-psycopg2
        state: present
    - name: Configure Databases
      ansible.builtin.include_tasks: database_config.yml
      loop: "{{ database_names }}"
    - name: Create Roles
      ansible.builtin.include_tasks: azure_ad_role_config.yml
      loop: "{{ database_names }}"