- name: Db Config
  hosts: localhost
  vars:
    common_config:
        login_host: 10.88.0.8
        login_user: admin
        login_password: admin
    database_names:
      - testdata
      - testdata_2

  tasks:
    - name: Utility present
      ansible.builtin.package:
        name: python3-psycopg2
        state: present
    - name: Configure Databases
      ansible.builtin.include_tasks: database_config.yml
      loop: "{{ database_names }}"
    - name: Create Roles
      ansible.builtin.include_tasks: azure_ad_role_config.yml
      loop: "{{ database_names }}"