---
- name: Demo 
  hosts: localhost
  tasks:
    - name: Utility present
      ansible.builtin.package:
        name: python3-psycopg2
        state: present
    - name: Create Role
      community.postgresql.postgresql_user:
        login_host: 10.88.0.8
        login_user: admin
        login_password: admin
        name: test_user
        password: hello
        role_attr_flags: LOGIN
    - name: Add to AzureAD
      community.postgresql.postgresql_membership:
        login_host: 10.88.0.8
        login_user: admin
        login_password: admin
        groups:
        - azure_ad_user
        target_role: test_user
        state: present
    - name: Give Permissions To Role
      community.postgresql.postgresql_privs:
        login_host: 10.88.0.8
        login_user: admin
        login_password: admin
        database: testdata
        state: present
        privs: CONNECT
        type: database
        role: test_user