name: Ansible Playbook Run

on:
  workflow_dispatch:
    inputs:
      hello_world:
        description: 'print something from ansible'  
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      ansible:
        image: docker.io/morinslash/ansible-psql-azure:v1
        options: --mount type=bind,source="${{ github.workspace }}",target=/ansible --name ansible

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: list running containers
      run: |
        ls

    - name: Run Ansible Playbook
      env:
        HELLO_WORLD: ${{ github.event.inputs.hello_world }}
      run: |
        docker exec ansible ansible-playbook src/ansible/test-script/github.yml -e '{"hello_world":"'${HELLO_WORLD}'"}'
